### PR TITLE
Created api.json w/MuleSoft Transform conference

### PR DESCRIPTION
**Pull request by alexandramartinez**
I tried to add this topic to the conference from the website, but I received an error.
Creating the file manually and adding the conference information here. 

Let me know if I missed anything!

### CODE REVIEW

**Comment by nimzco** [comment]
Oh! I should work on these error messages 😅
It's because the conference already exists.

image

**Comment by nimzco** [comment]
Thank you for your contribution though!

**Comment by nimzco** [comment]
Damnit, I speak too quickly. Let's merge that in so the API tag is added to it.

The way the backend is currently coded don't permit that through the form...

**Comment by nimzco** [comment]
I forgot to add the api topic in this repo. I'll do it right away and we'll be able to merge :)

**Comment by nimzco** [comment]
Could you rebase your branch? It should be good to go after that. :)

**Comment by alexandramartinez** [comment]
Done!

**Comment by nimzco** [comment]
Awesome! Team work! 🙌🏼

**Comment by nimzco** [comment]
It'll take a few before it updates on confs.tech, but it should soon!

**Pull request merged**
