### PR TITLE
Added test for country name

### PR DESCRIPTION
**Pull request by nimzco**

### CODE REVIEW

**Comment by cgrail** [comment]
@nimzco instead of doing a black list, we could also do a white list of allowed countries. This might be less error prone.

**Comment by nimzco** [comment]
Totally agree, I thought about that and got super lazy actually... but yes!

**Comment by nimzco** [comment]
And I can’t rebase this branch because I only have a phone with me 😭

**Comment by nimzco** [comment]
Thanks @cgrail!

**Pull request merged**
