### PR TITLE
chore: Add mastodon validation to checkConference.js

### LINKED ISSUE #6810: Improve Twitter usernames validate in tests
I notice that the Twitter usernames validate could be improve by making sure it gets formatted like `@twitter` and not `@@twitter` or `something@twitter`

To ensure there is only one "@" at the beginning of the Twitter username, you can modify the regular expression to start with the beginning of the line assertion (^). This will ensure that the "@" must be the first character in the string. Here's the updated regular expression:

`const twitterRegex = /^@\w([\w\.]){1,15}$/;`

This regular expression will match any string that starts with exactly one "@" followed by 1 to 15 word characters or periods, and nothing else.

after running the test locally, it found these errors: 
image

### PR DESCRIPTION
**Pull request by JuanPabloDiaz**
Improve Twitter usernames validate in tests
fixes #6810

Thanks for creating a new Pull Request for this repository.

To get the conferce as fast as possible into confs.tech please consider the following things.

## Checklist for your change
- [x] does not delete another conference
- [x] has passed the tests via `npm run test`
- [ ] has the correct order via `npm run reorder-confs`
- [ ] is a developer conference: more than 3-4 people from different companies
- [ ] is not a webinar, hackathon, marketing, zoom meeting with one person
- [ ] URLs are reachable, as short as possible, do not contain tracking parameters and the website is dedicated for this event
- [ ] topic is correct
- [ ] conference name is as short as possible and does not include location and date

### CODE REVIEW

**Comment by JuanPabloDiaz** [comment]
image

**Comment by cgrail** [comment]
@JuanPabloDiaz please always run `npm run reorder-confs` before commiting/pushing anything to the repo. Otherwise you get really ugly merge conflicts.
If you want to manually add conferences via the json files always run `npm run reorder-confs`. It will not only keep the conferences in the right order and their attributes, but it will also use the right spaces or tabs. 
I don't really enjoy fixing merge conflicts.

**Comment by JuanPabloDiaz** [comment]
> @JuanPabloDiaz please always run `npm run reorder-confs` before commiting/pushing anything to the repo. Otherwise you get really ugly merge conflicts. If you want to manually add conferences via the json files always run `npm run reorder-confs`. It will not only keep the conferences in the right order and their attributes, but it will also use the right spaces or tabs. I don't really enjoy fixing merge conflicts.

I will do that then; I was purposely not running it because I had the impression that it was messing up the indentations.
**I will always run it now**.

**Comment by cgrail** [comment]
Thanks a lot. It's not messing indentations up, it's rather fixing messed up indentation.

You've done a lot of great work recently. I'm happy to have you on board.

**Pull request merged**
