### PR TITLE
Removed duplicate event and marked this year's as postponed

### PR DESCRIPTION
**Pull request by jasongaylord**
Postponed this year's event due to covid and removed the duplicate event.

### CODE REVIEW

**Comment by nimzco** [comment]
Hi @jasongaylord, thanks for this update.

Instead of adding "POSTPONED" to the conference, do you have an idea of when the new date will be? Even if you need to update it later?

If not, I would rather remove the conference from the list. We can also tweet or retweet the info on our Twitter account.

**Comment by jasongaylord** [comment]
As of now, we don't have the dates set. We're waiting for options. It will be in 2022, but not sure when.

**Comment by nimzco** [comment]
Then if that's ok with you, let's remove the conference for now and let us know when you have a new date.

Thanks @jasongaylord!

**Comment by nimzco** [comment]
I'll close this in favor of https://github.com/tech-conferences/conference-data/pull/3754. Thanks again!

**Pull request closed without merging**
