### PR TITLE
Added Groovy as technology

### PR DESCRIPTION
**Pull request by sbglasius**
moved GR8Conf from Java to Groovy and added Greachconf to Groovy

### CODE REVIEW

**Comment by cgrail** [comment]
@nimzco can you please help?

**Comment by nimzco** [comment]
For sure. Thank you @sbglasius for your PR.
Could you also add the topic on confs.tech as well, like we did on this PR: https://github.com/tech-conferences/confs.tech/pull/422/files? That way people will see it in the dropdown when adding a conference.

I'll add the topic on the backend, so everything is good to go 👍 

Thanks again!

**Comment by sbglasius** [comment]
@nimzco Did the update here: https://github.com/tech-conferences/confs.tech/pull/431 and also added Groovy to this PR README.md

**Comment by cgrail** [comment]
Thanks a lot.

**Pull request merged**
