### PR TITLE
Add FEConf 2019

### PR DESCRIPTION
**Pull request by prigara**

### CODE REVIEW

**Comment by cgrail** [comment]
Thanks @prigara 
I'm waiting for the CFP for this conference. I want to submit a talk and speak there. I've never been in Korea.

**Comment by prigara** [comment]
Yeah, there's also [JSConf Korea](https://2019.jsconfkorea.com/en/) this year, but it's in 3 months and the CFP might have already closed.
My Korean colleague is in touch with organisers of FEConf, I will ask her to ask them about the CFP.

**Comment by prigara** [comment]
@cgrail FEConf will announce CFP next week.

**Comment by cgrail** [comment]
👍

**Pull request merged**
