### PR TITLE
Add Devopsdays Amsterdam 2021

### PR DESCRIPTION
**Pull request by FloorD**
Mark my commit - it's coming (full disclosure: I'm one of the organizers 😜 )

### CODE REVIEW

**Comment by PaulusTM** [comment]
for reference this is the open PR on the devopsdays repo: https://github.com/devopsdays/devopsdays-web/pull/10202

**Comment by cgrail** [comment]
Cool Thanks a lot.

**Review by cgrail — APPROVED** [review]

**Review by cgrail — APPROVED** [review]

**Comment by cgrail** [comment]
The site was just updated.

Thanks again for the PR @FloorD  and @PaulusTM

**Comment by nimzco** [comment]
🙌🏼

**Pull request merged**
