### PR TITLE
Update javascript.json

### PR DESCRIPTION
**Pull request by eugenelim**
add state as an optional parameter

### CODE REVIEW

**Comment by prigara** [comment]
@eugenelim thanks for the PR.
@nimzco, @cgrail I imagine we would need to make quite a few changes on the website to add this new field (e.g. conference submission form, items presentation...). What's your opinion on that?

**Comment by cgrail** [comment]
I would stay with the current format to have state as part of city e.g. ```San Francisco, CA```.

We would need state as a dedicated a parameter if we want to filter by state. Is there a use-case for that?

**Comment by nimzco** [comment]
Going down that road might add too much complexity for not much gain. I prefer sticking with our current approach. Also, if we were to add another field, I would call it `zone` as `state` only works for the US. Canada has provinces, other countries have regions, and it's only relevant for some countries to show it.

But thank you for the PR @eugenelim, I really appreciate it 🙏

**Comment by eugenelim** [comment]
I would support that - would it be ok to update the PR to use zone instead of state? I would like to filter by city, and the data is currently inconsistent in city. For example, some entries have "Chicago, IL" while some others have "Chicago".

The UI can be updated as a second pass.

**Comment by nimzco** [comment]
Oh I see your usecase. The only problem is that the city field is a free text field on the form (https://confs.tech/conferences/new), so people might still add the state like that. :/
Maybe you'd want to split on the comma if the country is `U.S.A.` instead?

**Comment by eugenelim** [comment]
If the form had zone introduced in the future, it would limit the state being added to the city.
And hopefully the PR reviews will catch it if we standardize on the new field. :)

**Comment by prigara** [comment]
Maybe we should get rid of the states in the conference data completely? I know it's common to add a state next to the city name, but is it really helpful? I'm not sure people would search conferences by the state - often it might be easier to go to another state from your location than to visit another city in the same state...

**Comment by eugenelim** [comment]
I was hoping to be able to find all conferences in my state, or be able to filter by nearby conferences. If we get rid of state from the city field and have the zone field as optional, it would meet both use cases.

**Comment by cgrail** [comment]
Any updates on this? Or should we close this PR?

**Comment by nimzco** [comment]
I’m in favor of closing. Sorry @eugenelim, I hope you found a solution for your use case.

**Pull request closed without merging**
