### PR TITLE
add conferences and CoC info to General

### PR DESCRIPTION
**Pull request by FloorD**

### CODE REVIEW

**Comment by FloorD** [comment]
Additional question: how can we reflect that an event is a hybrid event, so with both an in-person and online element to it?

**Comment by prigara** [comment]
@FloorD good question. It seems that we need to support having an array of locations.

**Comment by prigara** [comment]
@FloorD could you please remove the years from the event names so that the tests pass? Thank you!

**Comment by prigara** [comment]
Thank you @FloorD! I've merged the changes!

**Pull request merged**
